### ISSUE TITLE
Asking informations

### ISSUE THREAD

**Issue by RoyaghRamo** [Hedius/DiscordVoiceStatus#1]
Hello, i'm trying to implement this repository to my discord server, but I only see `VOICESTATUS_TOKEN` & `VOICESTATUS_HOST` & `VOICESTATUS_PORT`.
Can you tell me where I can find those?

Thanks

**Comment by Hedius** [comment]
Token is your discord api token.

Host and port are the binding information for the built in webinterface. Those should  not be changed. Bind all within a container is totally fine.

**Comment by RoyaghRamo** [comment]
How can I retrieve my discord api token?

**Comment by Hedius** [comment]
https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by RoyaghRamo** [comment]
So it's not a discord api token, it's a bot token?

**Comment by Hedius** [comment]
A bot token is a discord api token.

You either access the discord api with user tokens or bot tokens.
