### ISSUE TITLE
Discord bot token not given?

### ISSUE THREAD

**Issue by TheTomik1** [Hedius/DiscordVoiceStatus#2]
I followed all the 3 installation instructions, but whenever I try to use `docker run` to start the application, I receive the following message: `DISCORD BOT TOKEN NOT GIVEN!`.

Am I doing something wrong as I am completely sure the env variable in compose file is not empty and I followed the 3rd instruction after adjusting the file?

**Comment by Hedius** [comment]
You have to use docker-compose up if you add the key to a file.


docker compose up -d should work tbh. I run the same config

**Comment by Hedius** [comment]
Can you share the command you are running without the discord api token?

**Comment by TheTomik1** [comment]
Yes. Whenever I run the command `docker compose up -d` it starts to recreate and does that successfully. After I try the run command, it still tells me the token is not given. 

How should I share the command exactly?

**Comment by Hedius** [comment]
messaged you on discord
